source 'https://github.com/Cocoapods/Specs.git'
platform :ios, '10.0'

target 'CocoapodsEmbedIJK' do
  use_frameworks! :linkage => :static
  pod 'ijkplayerssl', :git => 'https://gitee.com/changsanjiang/ijkplayer.git'
end

target 'WithoutIJK' do
  use_frameworks!

end

target 'ManualEmbedIJK' do
  use_frameworks!

end

target 'CocoapodsEmbedBoth' do
#  use_frameworks! :linkage => :static
  use_frameworks!

  pod 'APod', :path => '../APod'
#  pod 'ijkplayerssl', :git => 'https://gitee.com/changsanjiang/ijkplayer.git'
  pod 'NodeMediaClient', '2.4.2'
#  pod 'ZPod', :path => '../ZPod'
end
